language: python
python:
  - 2.6
  - 2.7
install:
  - ./.travis_setup
env:
  - DJANGO="django>=1.3,<1.4"
  - DJANGO="django>=1.4,<1.5"
  - DJANGO="https://www.djangoproject.com/download/1.5c1/tarball/#egg=Django" EASY_THUMBNAILS="-e git+git://github.com/SmileyChris/easy-thumbnails.git#egg=easy-thumbnails"
  - DJANGO="-e git+git://github.com/django/django.git#egg=Django" EASY_THUMBNAILS="-e git+git://github.com/SmileyChris/easy-thumbnails.git#egg=easy-thumbnails"
script: python setup.py test
matrix:
  allow_failures:
    - python: 2.6
      env: DJANGO="-e git+git://github.com/django/django.git#egg=Django" EASY_THUMBNAILS="-e git+git://github.com/SmileyChris/easy-thumbnails.git#egg=easy-thumbnails"
    - python: 2.7
      env: DJANGO="-e git+git://github.com/django/django.git#egg=Django" EASY_THUMBNAILS="-e git+git://github.com/SmileyChris/easy-thumbnails.git#egg=easy-thumbnails"
