language: python

sudo: true

before_install:
  - if [[ $FRONTEND == "true" ]]; then npm install; fi;
  - if [[ $FRONTEND == "true" ]]; then sudo apt-get update; fi;
  - if [[ $FRONTEND == "true" ]]; then sudo apt-get install nodejs npm; fi;

install:
  - pip install tox coveralls

# Explicit environments list here is a complete list of environments from tox.
# It is intentionally shortened.
# Django 1.9 and master branch builds are disabled as they are not supported yet.
env:
# enable when front-end tests will be merged
#  - FRONTEND=true
  - TOX_ENV=flake8
#  - TOX_ENV=py34-django19-thumbs2x
  - TOX_ENV=py34-django18-thumbs2x
  - TOX_ENV=py34-django17-thumbs2x
#  - TOX_ENV=py33-django19-thumbs2x
  - TOX_ENV=py33-django18-thumbs2x
  - TOX_ENV=py33-django17-thumbs2x
#  - TOX_ENV=py27-django19-thumbs2x
  - TOX_ENV=py27-django18-thumbs2x
  - TOX_ENV=py27-django17-thumbs2x
#  - TOX_ENV=py34-django19-custom_image-thumbs2x
#  - TOX_ENV=py34-django18-custom_image-thumbs2x
#  - TOX_ENV=py34-django17-custom_image-thumbs2x
#  - TOX_ENV=py34-django16-custom_image-thumbs2x
#  - TOX_ENV=py33-django19-custom_image-thumbs2x
#  - TOX_ENV=py33-django18-custom_image-thumbs2x
#  - TOX_ENV=py33-django17-custom_image-thumbs2x
#  - TOX_ENV=py33-django16-custom_image-thumbs2x
#  - TOX_ENV=py27-django19-custom_image-thumbs2x
  - TOX_ENV=py27-django18-custom_image-thumbs2x
  - TOX_ENV=py27-django17-custom_image-thumbs2x
#  - TOX_ENV=py27-django16-custom_image-thumbs2x
#  - TOX_ENV=py34-django16-thumbs1x
#  - TOX_ENV=py34-django15-thumbs1x
#  - TOX_ENV=py33-django16-thumbs1x
#  - TOX_ENV=py33-django15-thumbs1x
  - TOX_ENV=py27-django16-thumbs1x
  - TOX_ENV=py27-django15-thumbs1x
  - TOX_ENV=py26-django16-thumbs1x
  - TOX_ENV=py26-django15-thumbs1x
#  - TOX_ENV=py34-django_master-thumbs2x
#  - TOX_ENV=py33-django_master-thumbs2x
#  - TOX_ENV=py27-django_master-thumbs2x

script:
  - tox -e $TOX_ENV
# replace it with when front-end tests will be merged
#  - if [[ $TRAVIS_PYTHON_VERSION = "2.7" && $FRONTEND = "true" ]]; then gulp ci; else tox -e $TOX_ENV; fi;

after_success:
  - coveralls --config_file=coverage.rc
  - mkdir -p shippable/codecoverage && cp coverage.xml shippable/codecoverage/coverage.xml

matrix:
  allow_failures:
    - env: TOX_ENV=flake8
    - env: TOX_ENV=py34-django_master-thumbs2x
    - env: TOX_ENV=py33-django_master-thumbs2x
    - env: TOX_ENV=py27-django_master-thumbs2x
