language: python
python:
  - 2.6
  - 2.7
install:
  - ./.travis_setup
env:
  - DJANGO="django>=1.3,<1.4"
  - DJANGO="django>=1.4,<1.5"
  - DJANGO="-e git+git://github.com/django/django.git#egg=Django"
script: python setup.py test
matrix:
  allow_failures:
    - env: DJANGO="-e git+git://github.com/django/django.git#egg=Django"
